/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrioridadeIdIndexRouteImport } from './routes/prioridade.$id.index'
import { Route as PrioridadeIdAcaoRouteImport } from './routes/prioridade.$id.acao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioridadeIdIndexRoute = PrioridadeIdIndexRouteImport.update({
  id: '/prioridade/$id/',
  path: '/prioridade/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioridadeIdAcaoRoute = PrioridadeIdAcaoRouteImport.update({
  id: '/prioridade/$id/acao',
  path: '/prioridade/$id/acao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prioridade/$id/acao': typeof PrioridadeIdAcaoRoute
  '/prioridade/$id/': typeof PrioridadeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prioridade/$id/acao': typeof PrioridadeIdAcaoRoute
  '/prioridade/$id': typeof PrioridadeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prioridade/$id/acao': typeof PrioridadeIdAcaoRoute
  '/prioridade/$id/': typeof PrioridadeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prioridade/$id/acao' | '/prioridade/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prioridade/$id/acao' | '/prioridade/$id'
  id: '__root__' | '/' | '/prioridade/$id/acao' | '/prioridade/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrioridadeIdAcaoRoute: typeof PrioridadeIdAcaoRoute
  PrioridadeIdIndexRoute: typeof PrioridadeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prioridade/$id/': {
      id: '/prioridade/$id/'
      path: '/prioridade/$id'
      fullPath: '/prioridade/$id/'
      preLoaderRoute: typeof PrioridadeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prioridade/$id/acao': {
      id: '/prioridade/$id/acao'
      path: '/prioridade/$id/acao'
      fullPath: '/prioridade/$id/acao'
      preLoaderRoute: typeof PrioridadeIdAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrioridadeIdAcaoRoute: PrioridadeIdAcaoRoute,
  PrioridadeIdIndexRoute: PrioridadeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
